version: 2

dependencies:
  - type: js
    path: ./

      github_labels:
        - dependencies

      github_assignees:
        - djones

      related_pr_behavior: close

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run:  npm install @percy/cli
        run:  npm install @percy/selenium-webdriver

      - name: Run tests
        run: npm test

      - name: Visual Testing with Percy
        run:  npx percy exec -- mvn clean test -Dtest="appTests.AppTest"
